/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * PulseGurgaon News Platform API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  Ad,
  AdminLoginBody,
  AdminLoginResponse,
  AdsListResponse,
  AiSearchBody,
  AiSearchResponse,
  Blog,
  BlogListResponse,
  CategoriesResponse,
  CreateAdBody,
  CreateBlogBody,
  ErrorResponse,
  HealthStatus,
  ListBlogsParams,
  ListNewsParams,
  NewsArticle,
  NewsListResponse,
  NewsStats,
  RefreshResponse,
  SearchNewsParams,
  SearchResponse,
  SuccessResponse,
  TickerResponse,
  UpdateArticleBody,
  UpdateTickerBody,
} from "./api.schemas";

import { customFetch } from "../custom-fetch";
import type { ErrorType, BodyType } from "../custom-fetch";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Health check
 */
export const getHealthCheckUrl = () => {
  return `/api/healthz`;
};

export const healthCheck = async (
  options?: RequestInit,
): Promise<HealthStatus> => {
  return customFetch<HealthStatus>(getHealthCheckUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthCheckQueryKey = () => {
  return [`/api/healthz`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = ErrorType<unknown>;

/**
 * @summary Health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List news articles
 */
export const getListNewsUrl = (params?: ListNewsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/news?${stringifiedParams}`
    : `/api/news`;
};

export const listNews = async (
  params?: ListNewsParams,
  options?: RequestInit,
): Promise<NewsListResponse> => {
  return customFetch<NewsListResponse>(getListNewsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListNewsQueryKey = (params?: ListNewsParams) => {
  return [`/api/news`, ...(params ? [params] : [])] as const;
};

export const getListNewsQueryOptions = <
  TData = Awaited<ReturnType<typeof listNews>>,
  TError = ErrorType<unknown>,
>(
  params?: ListNewsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listNews>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListNewsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listNews>>> = ({
    signal,
  }) => listNews(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listNews>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListNewsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listNews>>
>;
export type ListNewsQueryError = ErrorType<unknown>;

/**
 * @summary List news articles
 */

export function useListNews<
  TData = Awaited<ReturnType<typeof listNews>>,
  TError = ErrorType<unknown>,
>(
  params?: ListNewsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listNews>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListNewsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get featured/top news articles
 */
export const getGetFeaturedNewsUrl = () => {
  return `/api/news/featured`;
};

export const getFeaturedNews = async (
  options?: RequestInit,
): Promise<NewsListResponse> => {
  return customFetch<NewsListResponse>(getGetFeaturedNewsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetFeaturedNewsQueryKey = () => {
  return [`/api/news/featured`] as const;
};

export const getGetFeaturedNewsQueryOptions = <
  TData = Awaited<ReturnType<typeof getFeaturedNews>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getFeaturedNews>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetFeaturedNewsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getFeaturedNews>>> = ({
    signal,
  }) => getFeaturedNews({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getFeaturedNews>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetFeaturedNewsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFeaturedNews>>
>;
export type GetFeaturedNewsQueryError = ErrorType<unknown>;

/**
 * @summary Get featured/top news articles
 */

export function useGetFeaturedNews<
  TData = Awaited<ReturnType<typeof getFeaturedNews>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getFeaturedNews>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetFeaturedNewsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get news platform statistics
 */
export const getGetNewsStatsUrl = () => {
  return `/api/news/stats`;
};

export const getNewsStats = async (
  options?: RequestInit,
): Promise<NewsStats> => {
  return customFetch<NewsStats>(getGetNewsStatsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetNewsStatsQueryKey = () => {
  return [`/api/news/stats`] as const;
};

export const getGetNewsStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getNewsStats>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getNewsStats>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetNewsStatsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getNewsStats>>> = ({
    signal,
  }) => getNewsStats({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getNewsStats>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetNewsStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getNewsStats>>
>;
export type GetNewsStatsQueryError = ErrorType<unknown>;

/**
 * @summary Get news platform statistics
 */

export function useGetNewsStats<
  TData = Awaited<ReturnType<typeof getNewsStats>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getNewsStats>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetNewsStatsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get available news categories with counts
 */
export const getGetNewsCategoriesUrl = () => {
  return `/api/news/categories`;
};

export const getNewsCategories = async (
  options?: RequestInit,
): Promise<CategoriesResponse> => {
  return customFetch<CategoriesResponse>(getGetNewsCategoriesUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetNewsCategoriesQueryKey = () => {
  return [`/api/news/categories`] as const;
};

export const getGetNewsCategoriesQueryOptions = <
  TData = Awaited<ReturnType<typeof getNewsCategories>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getNewsCategories>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetNewsCategoriesQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getNewsCategories>>
  > = ({ signal }) => getNewsCategories({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getNewsCategories>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetNewsCategoriesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getNewsCategories>>
>;
export type GetNewsCategoriesQueryError = ErrorType<unknown>;

/**
 * @summary Get available news categories with counts
 */

export function useGetNewsCategories<
  TData = Awaited<ReturnType<typeof getNewsCategories>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getNewsCategories>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetNewsCategoriesQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get a single news article by ID
 */
export const getGetNewsByIdUrl = (id: number) => {
  return `/api/news/${id}`;
};

export const getNewsById = async (
  id: number,
  options?: RequestInit,
): Promise<NewsArticle> => {
  return customFetch<NewsArticle>(getGetNewsByIdUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetNewsByIdQueryKey = (id: number) => {
  return [`/api/news/${id}`] as const;
};

export const getGetNewsByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getNewsById>>,
  TError = ErrorType<ErrorResponse>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getNewsById>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetNewsByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getNewsById>>> = ({
    signal,
  }) => getNewsById(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getNewsById>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetNewsByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getNewsById>>
>;
export type GetNewsByIdQueryError = ErrorType<ErrorResponse>;

/**
 * @summary Get a single news article by ID
 */

export function useGetNewsById<
  TData = Awaited<ReturnType<typeof getNewsById>>,
  TError = ErrorType<ErrorResponse>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getNewsById>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetNewsByIdQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Manually trigger news fetch and AI enhancement
 */
export const getRefreshNewsUrl = () => {
  return `/api/news/refresh`;
};

export const refreshNews = async (
  options?: RequestInit,
): Promise<RefreshResponse> => {
  return customFetch<RefreshResponse>(getRefreshNewsUrl(), {
    ...options,
    method: "POST",
  });
};

export const getRefreshNewsMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof refreshNews>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof refreshNews>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["refreshNews"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof refreshNews>>,
    void
  > = () => {
    return refreshNews(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RefreshNewsMutationResult = NonNullable<
  Awaited<ReturnType<typeof refreshNews>>
>;

export type RefreshNewsMutationError = ErrorType<unknown>;

/**
 * @summary Manually trigger news fetch and AI enhancement
 */
export const useRefreshNews = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof refreshNews>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof refreshNews>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getRefreshNewsMutationOptions(options));
};

/**
 * @summary Search news by keyword and/or date range
 */
export const getSearchNewsUrl = (params?: SearchNewsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/search?${stringifiedParams}`
    : `/api/search`;
};

export const searchNews = async (
  params?: SearchNewsParams,
  options?: RequestInit,
): Promise<SearchResponse> => {
  return customFetch<SearchResponse>(getSearchNewsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getSearchNewsQueryKey = (params?: SearchNewsParams) => {
  return [`/api/search`, ...(params ? [params] : [])] as const;
};

export const getSearchNewsQueryOptions = <
  TData = Awaited<ReturnType<typeof searchNews>>,
  TError = ErrorType<unknown>,
>(
  params?: SearchNewsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof searchNews>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSearchNewsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof searchNews>>> = ({
    signal,
  }) => searchNews(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchNews>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type SearchNewsQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchNews>>
>;
export type SearchNewsQueryError = ErrorType<unknown>;

/**
 * @summary Search news by keyword and/or date range
 */

export function useSearchNews<
  TData = Awaited<ReturnType<typeof searchNews>>,
  TError = ErrorType<unknown>,
>(
  params?: SearchNewsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof searchNews>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getSearchNewsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary AI-powered smart search with natural language queries
 */
export const getAiSearchUrl = () => {
  return `/api/search/ai`;
};

export const aiSearch = async (
  aiSearchBody: AiSearchBody,
  options?: RequestInit,
): Promise<AiSearchResponse> => {
  return customFetch<AiSearchResponse>(getAiSearchUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(aiSearchBody),
  });
};

export const getAiSearchMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aiSearch>>,
    TError,
    { data: BodyType<AiSearchBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof aiSearch>>,
  TError,
  { data: BodyType<AiSearchBody> },
  TContext
> => {
  const mutationKey = ["aiSearch"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof aiSearch>>,
    { data: BodyType<AiSearchBody> }
  > = (props) => {
    const { data } = props ?? {};

    return aiSearch(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AiSearchMutationResult = NonNullable<
  Awaited<ReturnType<typeof aiSearch>>
>;
export type AiSearchMutationBody = BodyType<AiSearchBody>;
export type AiSearchMutationError = ErrorType<unknown>;

/**
 * @summary AI-powered smart search with natural language queries
 */
export const useAiSearch = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aiSearch>>,
    TError,
    { data: BodyType<AiSearchBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof aiSearch>>,
  TError,
  { data: BodyType<AiSearchBody> },
  TContext
> => {
  return useMutation(getAiSearchMutationOptions(options));
};

/**
 * @summary List all blogs
 */
export const getListBlogsUrl = (params?: ListBlogsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/blogs?${stringifiedParams}`
    : `/api/blogs`;
};

export const listBlogs = async (
  params?: ListBlogsParams,
  options?: RequestInit,
): Promise<BlogListResponse> => {
  return customFetch<BlogListResponse>(getListBlogsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListBlogsQueryKey = (params?: ListBlogsParams) => {
  return [`/api/blogs`, ...(params ? [params] : [])] as const;
};

export const getListBlogsQueryOptions = <
  TData = Awaited<ReturnType<typeof listBlogs>>,
  TError = ErrorType<unknown>,
>(
  params?: ListBlogsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listBlogs>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListBlogsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listBlogs>>> = ({
    signal,
  }) => listBlogs(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listBlogs>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListBlogsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listBlogs>>
>;
export type ListBlogsQueryError = ErrorType<unknown>;

/**
 * @summary List all blogs
 */

export function useListBlogs<
  TData = Awaited<ReturnType<typeof listBlogs>>,
  TError = ErrorType<unknown>,
>(
  params?: ListBlogsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listBlogs>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListBlogsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a new blog post
 */
export const getCreateBlogUrl = () => {
  return `/api/blogs`;
};

export const createBlog = async (
  createBlogBody: CreateBlogBody,
  options?: RequestInit,
): Promise<Blog> => {
  return customFetch<Blog>(getCreateBlogUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createBlogBody),
  });
};

export const getCreateBlogMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createBlog>>,
    TError,
    { data: BodyType<CreateBlogBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createBlog>>,
  TError,
  { data: BodyType<CreateBlogBody> },
  TContext
> => {
  const mutationKey = ["createBlog"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createBlog>>,
    { data: BodyType<CreateBlogBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createBlog(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateBlogMutationResult = NonNullable<
  Awaited<ReturnType<typeof createBlog>>
>;
export type CreateBlogMutationBody = BodyType<CreateBlogBody>;
export type CreateBlogMutationError = ErrorType<unknown>;

/**
 * @summary Create a new blog post
 */
export const useCreateBlog = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createBlog>>,
    TError,
    { data: BodyType<CreateBlogBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createBlog>>,
  TError,
  { data: BodyType<CreateBlogBody> },
  TContext
> => {
  return useMutation(getCreateBlogMutationOptions(options));
};

/**
 * @summary Get a single blog post
 */
export const getGetBlogByIdUrl = (id: number) => {
  return `/api/blogs/${id}`;
};

export const getBlogById = async (
  id: number,
  options?: RequestInit,
): Promise<Blog> => {
  return customFetch<Blog>(getGetBlogByIdUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetBlogByIdQueryKey = (id: number) => {
  return [`/api/blogs/${id}`] as const;
};

export const getGetBlogByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getBlogById>>,
  TError = ErrorType<ErrorResponse>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getBlogById>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetBlogByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getBlogById>>> = ({
    signal,
  }) => getBlogById(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getBlogById>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetBlogByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBlogById>>
>;
export type GetBlogByIdQueryError = ErrorType<ErrorResponse>;

/**
 * @summary Get a single blog post
 */

export function useGetBlogById<
  TData = Awaited<ReturnType<typeof getBlogById>>,
  TError = ErrorType<ErrorResponse>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getBlogById>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetBlogByIdQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update a blog post
 */
export const getUpdateBlogUrl = (id: number) => {
  return `/api/blogs/${id}`;
};

export const updateBlog = async (
  id: number,
  createBlogBody: CreateBlogBody,
  options?: RequestInit,
): Promise<Blog> => {
  return customFetch<Blog>(getUpdateBlogUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createBlogBody),
  });
};

export const getUpdateBlogMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateBlog>>,
    TError,
    { id: number; data: BodyType<CreateBlogBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateBlog>>,
  TError,
  { id: number; data: BodyType<CreateBlogBody> },
  TContext
> => {
  const mutationKey = ["updateBlog"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateBlog>>,
    { id: number; data: BodyType<CreateBlogBody> }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateBlog(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateBlogMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateBlog>>
>;
export type UpdateBlogMutationBody = BodyType<CreateBlogBody>;
export type UpdateBlogMutationError = ErrorType<unknown>;

/**
 * @summary Update a blog post
 */
export const useUpdateBlog = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateBlog>>,
    TError,
    { id: number; data: BodyType<CreateBlogBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateBlog>>,
  TError,
  { id: number; data: BodyType<CreateBlogBody> },
  TContext
> => {
  return useMutation(getUpdateBlogMutationOptions(options));
};

/**
 * @summary Delete a blog post
 */
export const getDeleteBlogUrl = (id: number) => {
  return `/api/blogs/${id}`;
};

export const deleteBlog = async (
  id: number,
  options?: RequestInit,
): Promise<SuccessResponse> => {
  return customFetch<SuccessResponse>(getDeleteBlogUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteBlogMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteBlog>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteBlog>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteBlog"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteBlog>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteBlog(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteBlogMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteBlog>>
>;

export type DeleteBlogMutationError = ErrorType<unknown>;

/**
 * @summary Delete a blog post
 */
export const useDeleteBlog = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteBlog>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteBlog>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeleteBlogMutationOptions(options));
};

/**
 * @summary Admin login
 */
export const getAdminLoginUrl = () => {
  return `/api/admin/login`;
};

export const adminLogin = async (
  adminLoginBody: AdminLoginBody,
  options?: RequestInit,
): Promise<AdminLoginResponse> => {
  return customFetch<AdminLoginResponse>(getAdminLoginUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(adminLoginBody),
  });
};

export const getAdminLoginMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminLogin>>,
    TError,
    { data: BodyType<AdminLoginBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminLogin>>,
  TError,
  { data: BodyType<AdminLoginBody> },
  TContext
> => {
  const mutationKey = ["adminLogin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminLogin>>,
    { data: BodyType<AdminLoginBody> }
  > = (props) => {
    const { data } = props ?? {};

    return adminLogin(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminLogin>>
>;
export type AdminLoginMutationBody = BodyType<AdminLoginBody>;
export type AdminLoginMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Admin login
 */
export const useAdminLogin = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminLogin>>,
    TError,
    { data: BodyType<AdminLoginBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof adminLogin>>,
  TError,
  { data: BodyType<AdminLoginBody> },
  TContext
> => {
  return useMutation(getAdminLoginMutationOptions(options));
};

/**
 * @summary Edit an article
 */
export const getUpdateArticleUrl = (id: number) => {
  return `/api/admin/articles/${id}`;
};

export const updateArticle = async (
  id: number,
  updateArticleBody: UpdateArticleBody,
  options?: RequestInit,
): Promise<NewsArticle> => {
  return customFetch<NewsArticle>(getUpdateArticleUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateArticleBody),
  });
};

export const getUpdateArticleMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateArticle>>,
    TError,
    { id: number; data: BodyType<UpdateArticleBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateArticle>>,
  TError,
  { id: number; data: BodyType<UpdateArticleBody> },
  TContext
> => {
  const mutationKey = ["updateArticle"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateArticle>>,
    { id: number; data: BodyType<UpdateArticleBody> }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateArticle(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateArticleMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateArticle>>
>;
export type UpdateArticleMutationBody = BodyType<UpdateArticleBody>;
export type UpdateArticleMutationError = ErrorType<unknown>;

/**
 * @summary Edit an article
 */
export const useUpdateArticle = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateArticle>>,
    TError,
    { id: number; data: BodyType<UpdateArticleBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateArticle>>,
  TError,
  { id: number; data: BodyType<UpdateArticleBody> },
  TContext
> => {
  return useMutation(getUpdateArticleMutationOptions(options));
};

/**
 * @summary Delete an article
 */
export const getDeleteArticleUrl = (id: number) => {
  return `/api/admin/articles/${id}`;
};

export const deleteArticle = async (
  id: number,
  options?: RequestInit,
): Promise<SuccessResponse> => {
  return customFetch<SuccessResponse>(getDeleteArticleUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteArticleMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteArticle>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteArticle>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteArticle"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteArticle>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteArticle(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteArticleMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteArticle>>
>;

export type DeleteArticleMutationError = ErrorType<unknown>;

/**
 * @summary Delete an article
 */
export const useDeleteArticle = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteArticle>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteArticle>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeleteArticleMutationOptions(options));
};

/**
 * @summary Get ticker text
 */
export const getGetTickerUrl = () => {
  return `/api/settings/ticker`;
};

export const getTicker = async (
  options?: RequestInit,
): Promise<TickerResponse> => {
  return customFetch<TickerResponse>(getGetTickerUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetTickerQueryKey = () => {
  return [`/api/settings/ticker`] as const;
};

export const getGetTickerQueryOptions = <
  TData = Awaited<ReturnType<typeof getTicker>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getTicker>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTickerQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTicker>>> = ({
    signal,
  }) => getTicker({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getTicker>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetTickerQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTicker>>
>;
export type GetTickerQueryError = ErrorType<unknown>;

/**
 * @summary Get ticker text
 */

export function useGetTicker<
  TData = Awaited<ReturnType<typeof getTicker>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getTicker>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetTickerQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update ticker text
 */
export const getUpdateTickerUrl = () => {
  return `/api/settings/ticker`;
};

export const updateTicker = async (
  updateTickerBody: UpdateTickerBody,
  options?: RequestInit,
): Promise<TickerResponse> => {
  return customFetch<TickerResponse>(getUpdateTickerUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateTickerBody),
  });
};

export const getUpdateTickerMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateTicker>>,
    TError,
    { data: BodyType<UpdateTickerBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateTicker>>,
  TError,
  { data: BodyType<UpdateTickerBody> },
  TContext
> => {
  const mutationKey = ["updateTicker"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateTicker>>,
    { data: BodyType<UpdateTickerBody> }
  > = (props) => {
    const { data } = props ?? {};

    return updateTicker(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateTickerMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateTicker>>
>;
export type UpdateTickerMutationBody = BodyType<UpdateTickerBody>;
export type UpdateTickerMutationError = ErrorType<unknown>;

/**
 * @summary Update ticker text
 */
export const useUpdateTicker = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateTicker>>,
    TError,
    { data: BodyType<UpdateTickerBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateTicker>>,
  TError,
  { data: BodyType<UpdateTickerBody> },
  TContext
> => {
  return useMutation(getUpdateTickerMutationOptions(options));
};

/**
 * @summary Get all ads
 */
export const getListAdsUrl = () => {
  return `/api/settings/ads`;
};

export const listAds = async (
  options?: RequestInit,
): Promise<AdsListResponse> => {
  return customFetch<AdsListResponse>(getListAdsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListAdsQueryKey = () => {
  return [`/api/settings/ads`] as const;
};

export const getListAdsQueryOptions = <
  TData = Awaited<ReturnType<typeof listAds>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof listAds>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListAdsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listAds>>> = ({
    signal,
  }) => listAds({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listAds>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListAdsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listAds>>
>;
export type ListAdsQueryError = ErrorType<unknown>;

/**
 * @summary Get all ads
 */

export function useListAds<
  TData = Awaited<ReturnType<typeof listAds>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof listAds>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListAdsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create an ad
 */
export const getCreateAdUrl = () => {
  return `/api/settings/ads`;
};

export const createAd = async (
  createAdBody: CreateAdBody,
  options?: RequestInit,
): Promise<Ad> => {
  return customFetch<Ad>(getCreateAdUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createAdBody),
  });
};

export const getCreateAdMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createAd>>,
    TError,
    { data: BodyType<CreateAdBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createAd>>,
  TError,
  { data: BodyType<CreateAdBody> },
  TContext
> => {
  const mutationKey = ["createAd"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createAd>>,
    { data: BodyType<CreateAdBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createAd(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateAdMutationResult = NonNullable<
  Awaited<ReturnType<typeof createAd>>
>;
export type CreateAdMutationBody = BodyType<CreateAdBody>;
export type CreateAdMutationError = ErrorType<unknown>;

/**
 * @summary Create an ad
 */
export const useCreateAd = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createAd>>,
    TError,
    { data: BodyType<CreateAdBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createAd>>,
  TError,
  { data: BodyType<CreateAdBody> },
  TContext
> => {
  return useMutation(getCreateAdMutationOptions(options));
};

/**
 * @summary Update an ad
 */
export const getUpdateAdUrl = (id: number) => {
  return `/api/settings/ads/${id}`;
};

export const updateAd = async (
  id: number,
  createAdBody: CreateAdBody,
  options?: RequestInit,
): Promise<Ad> => {
  return customFetch<Ad>(getUpdateAdUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createAdBody),
  });
};

export const getUpdateAdMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateAd>>,
    TError,
    { id: number; data: BodyType<CreateAdBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateAd>>,
  TError,
  { id: number; data: BodyType<CreateAdBody> },
  TContext
> => {
  const mutationKey = ["updateAd"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateAd>>,
    { id: number; data: BodyType<CreateAdBody> }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateAd(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateAdMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateAd>>
>;
export type UpdateAdMutationBody = BodyType<CreateAdBody>;
export type UpdateAdMutationError = ErrorType<unknown>;

/**
 * @summary Update an ad
 */
export const useUpdateAd = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateAd>>,
    TError,
    { id: number; data: BodyType<CreateAdBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateAd>>,
  TError,
  { id: number; data: BodyType<CreateAdBody> },
  TContext
> => {
  return useMutation(getUpdateAdMutationOptions(options));
};

/**
 * @summary Delete an ad
 */
export const getDeleteAdUrl = (id: number) => {
  return `/api/settings/ads/${id}`;
};

export const deleteAd = async (
  id: number,
  options?: RequestInit,
): Promise<SuccessResponse> => {
  return customFetch<SuccessResponse>(getDeleteAdUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteAdMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteAd>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteAd>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteAd"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteAd>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteAd(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteAdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteAd>>
>;

export type DeleteAdMutationError = ErrorType<unknown>;

/**
 * @summary Delete an ad
 */
export const useDeleteAd = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteAd>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteAd>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeleteAdMutationOptions(options));
};
