/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * PulseGurgaon News Platform API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface ErrorResponse {
  error: string;
}

export interface SuccessResponse {
  success: boolean;
}

export interface TimelineStep {
  step: number;
  title: string;
  description: string;
}

export interface VocabWord {
  word: string;
  meaning: string;
}

export interface NewsArticle {
  id: number;
  title: string;
  description: string;
  fullArticle: string;
  summaryPoints: string[];
  timeline: TimelineStep[];
  vocabulary: VocabWord[];
  category: string;
  image?: string | null;
  publishedAt: string;
  sourceUrl?: string | null;
  sourceName?: string | null;
  aiEnhanced: boolean;
  createdAt: string;
}

export interface NewsListResponse {
  articles: NewsArticle[];
  total: number;
  page: number;
  limit: number;
}

export type NewsStatsCategoryCounts = { [key: string]: number };

export interface NewsStats {
  totalArticles: number;
  totalBlogs: number;
  categoryCounts: NewsStatsCategoryCounts;
  lastRefreshed?: string | null;
}

export interface CategoryCount {
  name: string;
  count: number;
}

export interface CategoriesResponse {
  categories: CategoryCount[];
}

export interface RefreshResponse {
  message: string;
  newArticles: number;
}

export interface SearchResponse {
  articles: NewsArticle[];
  total: number;
  query: string;
}

export interface AiSearchBody {
  query: string;
}

export interface AiSearchResponse {
  articles: NewsArticle[];
  suggestedTopics: string[];
  interpretation: string;
}

export interface Blog {
  id: number;
  title: string;
  content: string;
  image?: string | null;
  category: string;
  excerpt: string;
  createdAt: string;
  updatedAt: string;
}

export interface BlogListResponse {
  blogs: Blog[];
  total: number;
  page: number;
  limit: number;
}

export interface CreateBlogBody {
  title: string;
  content: string;
  image?: string | null;
  category: string;
  excerpt: string;
}

export interface AdminLoginBody {
  username: string;
  password: string;
}

export interface AdminLoginResponse {
  success: boolean;
  token: string;
}

export interface UpdateArticleBody {
  title?: string;
  description?: string;
  fullArticle?: string;
  category?: string;
  image?: string | null;
}

export interface TickerResponse {
  text: string;
  enabled: boolean;
}

export interface UpdateTickerBody {
  text: string;
  enabled: boolean;
}

export interface Ad {
  id: number;
  title: string;
  imageUrl?: string | null;
  linkUrl?: string | null;
  placement: string;
  enabled: boolean;
  createdAt: string;
}

export interface AdsListResponse {
  ads: Ad[];
}

export interface CreateAdBody {
  title: string;
  imageUrl?: string | null;
  linkUrl?: string | null;
  placement: string;
  enabled: boolean;
}

export type ListNewsParams = {
  category?: string;
  page?: number;
  limit?: number;
};

export type SearchNewsParams = {
  q?: string;
  from?: string;
  to?: string;
  category?: string;
};

export type ListBlogsParams = {
  category?: string;
  page?: number;
  limit?: number;
};
