/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * PulseGurgaon News Platform API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary List news articles
 */
export const ListNewsQueryParams = zod.object({
  category: zod.coerce.string().optional(),
  page: zod.coerce.number().optional(),
  limit: zod.coerce.number().optional(),
});

export const ListNewsResponse = zod.object({
  articles: zod.array(
    zod.object({
      id: zod.number(),
      title: zod.string(),
      description: zod.string(),
      fullArticle: zod.string(),
      summaryPoints: zod.array(zod.string()),
      timeline: zod.array(
        zod.object({
          step: zod.number(),
          title: zod.string(),
          description: zod.string(),
        }),
      ),
      vocabulary: zod.array(
        zod.object({
          word: zod.string(),
          meaning: zod.string(),
        }),
      ),
      category: zod.string(),
      image: zod.string().nullish(),
      publishedAt: zod.string(),
      sourceUrl: zod.string().nullish(),
      sourceName: zod.string().nullish(),
      aiEnhanced: zod.boolean(),
      createdAt: zod.string(),
    }),
  ),
  total: zod.number(),
  page: zod.number(),
  limit: zod.number(),
});

/**
 * @summary Get featured/top news articles
 */
export const GetFeaturedNewsResponse = zod.object({
  articles: zod.array(
    zod.object({
      id: zod.number(),
      title: zod.string(),
      description: zod.string(),
      fullArticle: zod.string(),
      summaryPoints: zod.array(zod.string()),
      timeline: zod.array(
        zod.object({
          step: zod.number(),
          title: zod.string(),
          description: zod.string(),
        }),
      ),
      vocabulary: zod.array(
        zod.object({
          word: zod.string(),
          meaning: zod.string(),
        }),
      ),
      category: zod.string(),
      image: zod.string().nullish(),
      publishedAt: zod.string(),
      sourceUrl: zod.string().nullish(),
      sourceName: zod.string().nullish(),
      aiEnhanced: zod.boolean(),
      createdAt: zod.string(),
    }),
  ),
  total: zod.number(),
  page: zod.number(),
  limit: zod.number(),
});

/**
 * @summary Get news platform statistics
 */
export const GetNewsStatsResponse = zod.object({
  totalArticles: zod.number(),
  totalBlogs: zod.number(),
  categoryCounts: zod.record(zod.string(), zod.number()),
  lastRefreshed: zod.string().nullish(),
});

/**
 * @summary Get available news categories with counts
 */
export const GetNewsCategoriesResponse = zod.object({
  categories: zod.array(
    zod.object({
      name: zod.string(),
      count: zod.number(),
    }),
  ),
});

/**
 * @summary Get a single news article by ID
 */
export const GetNewsByIdParams = zod.object({
  id: zod.coerce.number(),
});

export const GetNewsByIdResponse = zod.object({
  id: zod.number(),
  title: zod.string(),
  description: zod.string(),
  fullArticle: zod.string(),
  summaryPoints: zod.array(zod.string()),
  timeline: zod.array(
    zod.object({
      step: zod.number(),
      title: zod.string(),
      description: zod.string(),
    }),
  ),
  vocabulary: zod.array(
    zod.object({
      word: zod.string(),
      meaning: zod.string(),
    }),
  ),
  category: zod.string(),
  image: zod.string().nullish(),
  publishedAt: zod.string(),
  sourceUrl: zod.string().nullish(),
  sourceName: zod.string().nullish(),
  aiEnhanced: zod.boolean(),
  createdAt: zod.string(),
});

/**
 * @summary Manually trigger news fetch and AI enhancement
 */
export const RefreshNewsResponse = zod.object({
  message: zod.string(),
  newArticles: zod.number(),
});

/**
 * @summary Search news by keyword and/or date range
 */
export const SearchNewsQueryParams = zod.object({
  q: zod.coerce.string().optional(),
  from: zod.coerce.string().optional(),
  to: zod.coerce.string().optional(),
  category: zod.coerce.string().optional(),
});

export const SearchNewsResponse = zod.object({
  articles: zod.array(
    zod.object({
      id: zod.number(),
      title: zod.string(),
      description: zod.string(),
      fullArticle: zod.string(),
      summaryPoints: zod.array(zod.string()),
      timeline: zod.array(
        zod.object({
          step: zod.number(),
          title: zod.string(),
          description: zod.string(),
        }),
      ),
      vocabulary: zod.array(
        zod.object({
          word: zod.string(),
          meaning: zod.string(),
        }),
      ),
      category: zod.string(),
      image: zod.string().nullish(),
      publishedAt: zod.string(),
      sourceUrl: zod.string().nullish(),
      sourceName: zod.string().nullish(),
      aiEnhanced: zod.boolean(),
      createdAt: zod.string(),
    }),
  ),
  total: zod.number(),
  query: zod.string(),
});

/**
 * @summary AI-powered smart search with natural language queries
 */
export const AiSearchBody = zod.object({
  query: zod.string(),
});

export const AiSearchResponse = zod.object({
  articles: zod.array(
    zod.object({
      id: zod.number(),
      title: zod.string(),
      description: zod.string(),
      fullArticle: zod.string(),
      summaryPoints: zod.array(zod.string()),
      timeline: zod.array(
        zod.object({
          step: zod.number(),
          title: zod.string(),
          description: zod.string(),
        }),
      ),
      vocabulary: zod.array(
        zod.object({
          word: zod.string(),
          meaning: zod.string(),
        }),
      ),
      category: zod.string(),
      image: zod.string().nullish(),
      publishedAt: zod.string(),
      sourceUrl: zod.string().nullish(),
      sourceName: zod.string().nullish(),
      aiEnhanced: zod.boolean(),
      createdAt: zod.string(),
    }),
  ),
  suggestedTopics: zod.array(zod.string()),
  interpretation: zod.string(),
});

/**
 * @summary List all blogs
 */
export const ListBlogsQueryParams = zod.object({
  category: zod.coerce.string().optional(),
  page: zod.coerce.number().optional(),
  limit: zod.coerce.number().optional(),
});

export const ListBlogsResponse = zod.object({
  blogs: zod.array(
    zod.object({
      id: zod.number(),
      title: zod.string(),
      content: zod.string(),
      image: zod.string().nullish(),
      category: zod.string(),
      excerpt: zod.string(),
      createdAt: zod.string(),
      updatedAt: zod.string(),
    }),
  ),
  total: zod.number(),
  page: zod.number(),
  limit: zod.number(),
});

/**
 * @summary Create a new blog post
 */
export const CreateBlogBody = zod.object({
  title: zod.string(),
  content: zod.string(),
  image: zod.string().nullish(),
  category: zod.string(),
  excerpt: zod.string(),
});

/**
 * @summary Get a single blog post
 */
export const GetBlogByIdParams = zod.object({
  id: zod.coerce.number(),
});

export const GetBlogByIdResponse = zod.object({
  id: zod.number(),
  title: zod.string(),
  content: zod.string(),
  image: zod.string().nullish(),
  category: zod.string(),
  excerpt: zod.string(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});

/**
 * @summary Update a blog post
 */
export const UpdateBlogParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateBlogBody = zod.object({
  title: zod.string(),
  content: zod.string(),
  image: zod.string().nullish(),
  category: zod.string(),
  excerpt: zod.string(),
});

export const UpdateBlogResponse = zod.object({
  id: zod.number(),
  title: zod.string(),
  content: zod.string(),
  image: zod.string().nullish(),
  category: zod.string(),
  excerpt: zod.string(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
});

/**
 * @summary Delete a blog post
 */
export const DeleteBlogParams = zod.object({
  id: zod.coerce.number(),
});

export const DeleteBlogResponse = zod.object({
  success: zod.boolean(),
});

/**
 * @summary Admin login
 */
export const AdminLoginBody = zod.object({
  username: zod.string(),
  password: zod.string(),
});

export const AdminLoginResponse = zod.object({
  success: zod.boolean(),
  token: zod.string(),
});

/**
 * @summary Edit an article
 */
export const UpdateArticleParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateArticleBody = zod.object({
  title: zod.string().optional(),
  description: zod.string().optional(),
  fullArticle: zod.string().optional(),
  category: zod.string().optional(),
  image: zod.string().nullish(),
});

export const UpdateArticleResponse = zod.object({
  id: zod.number(),
  title: zod.string(),
  description: zod.string(),
  fullArticle: zod.string(),
  summaryPoints: zod.array(zod.string()),
  timeline: zod.array(
    zod.object({
      step: zod.number(),
      title: zod.string(),
      description: zod.string(),
    }),
  ),
  vocabulary: zod.array(
    zod.object({
      word: zod.string(),
      meaning: zod.string(),
    }),
  ),
  category: zod.string(),
  image: zod.string().nullish(),
  publishedAt: zod.string(),
  sourceUrl: zod.string().nullish(),
  sourceName: zod.string().nullish(),
  aiEnhanced: zod.boolean(),
  createdAt: zod.string(),
});

/**
 * @summary Delete an article
 */
export const DeleteArticleParams = zod.object({
  id: zod.coerce.number(),
});

export const DeleteArticleResponse = zod.object({
  success: zod.boolean(),
});

/**
 * @summary Get ticker text
 */
export const GetTickerResponse = zod.object({
  text: zod.string(),
  enabled: zod.boolean(),
});

/**
 * @summary Update ticker text
 */
export const UpdateTickerBody = zod.object({
  text: zod.string(),
  enabled: zod.boolean(),
});

export const UpdateTickerResponse = zod.object({
  text: zod.string(),
  enabled: zod.boolean(),
});

/**
 * @summary Get all ads
 */
export const ListAdsResponse = zod.object({
  ads: zod.array(
    zod.object({
      id: zod.number(),
      title: zod.string(),
      imageUrl: zod.string().nullish(),
      linkUrl: zod.string().nullish(),
      placement: zod.string(),
      enabled: zod.boolean(),
      createdAt: zod.string(),
    }),
  ),
});

/**
 * @summary Create an ad
 */
export const CreateAdBody = zod.object({
  title: zod.string(),
  imageUrl: zod.string().nullish(),
  linkUrl: zod.string().nullish(),
  placement: zod.string(),
  enabled: zod.boolean(),
});

/**
 * @summary Update an ad
 */
export const UpdateAdParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateAdBody = zod.object({
  title: zod.string(),
  imageUrl: zod.string().nullish(),
  linkUrl: zod.string().nullish(),
  placement: zod.string(),
  enabled: zod.boolean(),
});

export const UpdateAdResponse = zod.object({
  id: zod.number(),
  title: zod.string(),
  imageUrl: zod.string().nullish(),
  linkUrl: zod.string().nullish(),
  placement: zod.string(),
  enabled: zod.boolean(),
  createdAt: zod.string(),
});

/**
 * @summary Delete an ad
 */
export const DeleteAdParams = zod.object({
  id: zod.coerce.number(),
});

export const DeleteAdResponse = zod.object({
  success: zod.boolean(),
});
