/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * PulseGurgaon News Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { Blog } from "./blog";

export interface BlogListResponse {
  blogs: Blog[];
  total: number;
  page: number;
  limit: number;
}
