/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * PulseGurgaon News Platform API
 * OpenAPI spec version: 0.1.0
 */

export * from "./ad";
export * from "./adminLoginBody";
export * from "./adminLoginResponse";
export * from "./adsListResponse";
export * from "./aiSearchBody";
export * from "./aiSearchResponse";
export * from "./blog";
export * from "./blogListResponse";
export * from "./categoriesResponse";
export * from "./categoryCount";
export * from "./createAdBody";
export * from "./createBlogBody";
export * from "./errorResponse";
export * from "./healthStatus";
export * from "./listBlogsParams";
export * from "./listNewsParams";
export * from "./newsArticle";
export * from "./newsListResponse";
export * from "./newsStats";
export * from "./newsStatsCategoryCounts";
export * from "./refreshResponse";
export * from "./searchNewsParams";
export * from "./searchResponse";
export * from "./successResponse";
export * from "./tickerResponse";
export * from "./timelineStep";
export * from "./updateArticleBody";
export * from "./updateTickerBody";
export * from "./vocabWord";
