/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * PulseGurgaon News Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { NewsStatsCategoryCounts } from "./newsStatsCategoryCounts";

export interface NewsStats {
  totalArticles: number;
  totalBlogs: number;
  categoryCounts: NewsStatsCategoryCounts;
  lastRefreshed?: string | null;
}
