/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * PulseGurgaon News Platform API
 * OpenAPI spec version: 0.1.0
 */

export type SearchNewsParams = {
  q?: string;
  from?: string;
  to?: string;
  category?: string;
};
